apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5200"
  POSTGRES_PORT: "55432"
  POSTGRES_DB: gh-sentry-2
  SENTRY_URL: https://sentry.io
  DEPLOYMENT_REQUESTS_HANDLER: https://gh-sentry-gate.subir.in/api/sentry/deployment-requests-handler
  RENEW_SENTRY_TOKENS_HANDLER: https://gh-sentry-gate.subir.in/api/sentry/renew-refresh-token
