kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-sentry-app
  template:
    metadata:
      labels:
        app: gh-sentry-app
    spec:
      containers:
        - name: backend
          image: github-sentry-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5200
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: POSTGRES_DB
            - name: SENTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SENTRY_URL
            - name: DEPLOYMENT_REQUESTS_HANDLER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DEPLOYMENT_REQUESTS_HANDLER
            - name: RENEW_SENTRY_TOKENS_HANDLER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RENEW_SENTRY_TOKENS_HANDLER
            # secrets
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_PASSWORD
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: SENTRY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SENTRY_CLIENT_ID
            - name: SENTRY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SENTRY_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GITHUB_APP_PRIVATE_KEY
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GITHUB_APP_ID
            - name: GITHUB_APP_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GITHUB_APP_WEBHOOK_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: gh-sentry-app
  ports:
    - port: 5200
      targetPort: 5200
